function [Jacobian,find_flip] = spline_distortion_Jac(sp,X)
% sp: spline object generated by spmak
% X: 2*n2*... array
% outputs:
% Jacobian: 1*N
% find_flip: True if any of Jacobian is negative
dx = fnval(fnder(sp,[1,0]),X);
dy = fnval(fnder(sp,[0,1]),X);
sz = size(X);
sz(1)=1;
Jacobian = zeros(sz);
Jacobian(:) = dx(1,:).*dy(2,:)-dx(2,:).*dy(1,:);
find_flip = any(Jacobian<-1e-6);
if any(isinf(Jacobian)) || any(isnan(Jacobian))
    find_flip = true;
end

end